# Generated by Django 3.2.5 on 2021-07-18 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjpost',
            name='context',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
