# Generated by Django 3.2.5 on 2021-07-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cj_app', '0002_cjpost_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cjpost',
            old_name='context',
            new_name='content',
        ),
    ]
